library(ranger)
library(caret)
library(data.table)
library(dplyr)
setwd("/Users/Soorya Suresh/Desktop/Data Analysis")
data<-read.csv("/Users/Soorya Suresh/Desktop/Data Analysis/CreditCard/creditcard.csv")
#explore data
head(data,10)
names(data)
tail(data,10)
range(data)
range(data$Amount)
range(data$Time)
range(data$Class)
summary(data)
summary(data$Amount)
summary(data$Time)
sd(data$Class)
sd(data$Amount)
sd(data)
table(data)
table(data$Amount)
table(data$Time)
table(data$Class)
cor(data)
dim(data)
glimpse(data)
#manipulate data
data$Amount=scale(data$Amount)
head(data)
new_data=data[,-c(1)]
head(new_data)
#model the data now
#conduct logistic regression to show a fraud/not fraud 
library(caTools)
set.seed(123)
spl<-sample.split(new_data$Class,SplitRatio=0.8)
Train<-subset(new_data,spl==TRUE)
Test<-subset(new_data,spl==FALSE)
dim(Train)
dim(Test)
model <- glm(Class ~.,Test,family=binomial())
summary(model)
anova(model)
plot(model)
